#image: java:8-jdk
image: maven:3-jdk-8

stages:
  - build
  - test
  - deploy

before_script:
  - echo $JAVA_HOME
  - export PATH="$JAVA_HOME/bin:$ANT_HOME/bin:$PATH"


maven-build:
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar


test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
#    - cd JavaProjects
#    - ./gradlew deploy
    - echo do not deploy!

after_script:
  - echo "End CI"